### ISSUE TITLE
can't open MHW Editor

### ISSUE THREAD

**Issue by s9778010** [Synthlight/MHW-Editor#12]
I try to open MHW editor many times. 
already install Microsoft. NET Framework 4.7.2.
but still can't open ...

**Comment by Synthlight** [comment]
I don't have a crystal ball. I NEED information to work with. An error message; just *something*.

Make sure you actually extract it from the zip before running it. The dlls must be present in the same directory as the exe, which doesn't happen if you try to run it from the zip. (This extracts just the exe to a temp folder before execution which doesn't include the dlls.)

**Comment by s9778010** [comment]
I  actually extract and open in the same directory as the exe.
but open the exe then nothing happened, no error message , no window pops out...

**Comment by Synthlight** [comment]
There's an error *somewhere*. Try Event Viewer (eventvwr.msc), in the Application log.

**Comment by Synthlight** [comment]
No information, no way to replicate, seems like an isolated case, and no further replies. Nothing I can do here. Closing.
Re-open if you manager to get an error msg from a log somewhere.
