### ISSUE TITLE
Json import for shop.sed broken on latest version (2.3)

### ISSUE THREAD

**Issue by albinodonkey** [Synthlight/MHW-Editor#16]
The editor opens and loads the file correctly, and saves changes to Json correctly as well. Upon importing the changes I am greeted by an error (https://pastebin.com/c58qhrCg).

Reverting to version 2.2 solved the issue

**Comment by Synthlight** [comment]
I'm going to need the json file, as well as which file you're applying it against.

**Comment by albinodonkey** [comment]
Sure thing.

[shop.zip](https://github.com/Synthlight/MHW-Editor/files/5043182/shop.zip)

**Comment by Synthlight** [comment]
Fixed in 2.3.1.
