### ISSUE TITLE
MHW version 14 JSON files that did not import correctly

### ISSUE THREAD

**Issue by Hellenicz** [Synthlight/MHW-Editor#18]
Hello Synthlight,

These are some of the JSON files that did not import from the 2.3.1 MHW Editor to the latest version for the 15.01 MHW update.

[14.00 JSON.zip](https://github.com/Synthlight/MHW-Editor/files/5331626/14.00.JSON.zip)

**Comment by Synthlight** [comment]
I've done some initial testing with armor, and it seems to work just fine.
Can you give me specific examples of something that isn't working?

**Comment by Synthlight** [comment]
"Damascus Greaves α+" is set group 430.
The json for 430 is this:
```
      "430|Alpha|Regular|Head": {
        "Skill_2": 81,
        "Skill_1": 21,
        "Set_Skill_1": 173,
        "Set_Skill_1_Level": 1
      },
      "430|Alpha|Regular|Chest": {
        "Skill_2_Level": 7,
        "Set_Skill_1": 173,
        "Set_Skill_1_Level": 1
      },
      "430|Alpha|Regular|Arms": {
        "Skill_1": 86,
        "Skill_1_Level": 3,
        "Skill_2": 158,
        "Slot_1_Size": 4,
        "Slot_2_Size": 2,
        "Set_Skill_1": 173,
        "Set_Skill_1_Level": 1
      },
      "430|Alpha|Regular|Waist": {
        "Skill_2": 22,
        "Skill_2_Level": 3,
        "Set_Skill_1": 173,
        "Set_Skill_1_Level": 1
      },
      "430|Alpha|Regular|Legs": {
        "Skill_1": 76,
        "Skill_2_Level": 3,
        "Set_Skill_1": 173,
        "Set_Skill_1_Level": 1
      },
```
There is absolutely nothing in there about skill 3 and thus it will never change.
Of what I see in the json, this is importing correctly. It looks like your json is incomplete if you're expecting it to alter skill 3.
If you still have the modded armor.am_dat from the previous update, send me that. I can recreate the json from it and double check things, but this appears to be working right.

Perhaps you didn't export the changes to slot 3 but just saved them to the file instead?

> Another kind regarding skills is that while most of them remain the same as what I saved as a JSON, there will be a default skill like earplugs level 2 on the Ruinous Greaves Alpha/Beta.

Ruinous Greaves Alpha/Beta: Set group is 453/454 so the json entries are these:
```
      "453|Alpha|Regular|Legs": {
        "Skill_2_Level": 2,
        "Slot_2_Size": 2
      },
      "454|Beta_or_Gamma|Regular|Legs": {
        "Skill_2": 62,
        "Skill_2_Level": 1
      },
```
Earplugs is default skill 1. There's nothing in the json changing skill 1. Again, evidence points to it importing correctly.

**Comment by Synthlight** [comment]
From the nexus comment thread:
> In fact, I ran a quick test and concluded that what must have happened is that I hit SAVE before hitting save merge to JSON. The program skipped over any changes in between merges because at some point I saved before merging.

Closing as not an issue.
