### ISSUE TITLE
Changes to wp07_param.w07p, wep_glan.weg_glan

### ISSUE THREAD

**Issue by Schinkikami** [Synthlight/MHW-Editor#19]
Hey been playing around with the tool its awesome thanks :)

So just 2 things I noticed, while playing around with the gunlance

wp07_param.w07p
﻿-  Unk322 seems to be the WSB damage multiplier for the uncharged shelling shots (I tested this)

wep_glan.weg_glan 
﻿- When using the editor all entries for Wide and Long seem to be confused. It says Long where it should say Wide and the other way around. For example, when looking into the 'Special Ability 1' coloumn: Nergal Ram has special ability '6' (which is Long 1 in the wep file, which would be called Long 2 in the game .. Zero indexing :D). But in the game it has Wide 2. This is also the case for the newly added Iceborn Tiers. The Wide 7 Gunlances have special ability 19, which is Long 7 in the wep file (but there are no Long 7 weapons in MHW). 

Not so sure where a post like this belongs.
Thanks for your hard work :)

**Comment by Synthlight** [comment]
Right, ok, so, I haven't touched gunlance since MH was on PSP. So keep that in mind when you tell me things.
Buy yea, this is the perfect spot for stuff like this.

So I added the field:
![image](https://user-images.githubusercontent.com/1075166/96674133-0e0fa480-1336-11eb-8cd3-eb750817b328.png)

And switched long & wide:
![image](https://user-images.githubusercontent.com/1075166/96674156-1962d000-1336-11eb-9c04-859368d07c74.png)

Poke me if this looks good, or you want anything else changed.

**Comment by Schinkikami** [comment]
This seems fine :)

**Comment by Schinkikami** [comment]
Hey some stuff for the lance now (wp06_param.w06p)

Unk91 is the startup speed of the Dash (Dash Lvl1 Speed)

Unk94, Unk95 and Unk98 are the looping speed of the running animation for the different charge levels (cranking them up lets you look like Sonic the Hedgehog :D)

Unk111  is the speed multiplier while gliding down slopes (while charging)

Now for the stuff I dont fully understand: 

unk104 controls under which degree (when running against a wall) you bounce off, ending the charge. Setting it to 0 prevents bounce offs from happening at all. But I'm not sure what the unit there is exactly. 

unk101 has something to do with the steering not sure how it should even be called. Setting it to a high number (from 30 up to 100 for example) lowers your ability to steer the charge. Not sure if and how you should add that.

**Comment by Synthlight** [comment]
> unk104 controls under which degree (when running against a wall) you bounce off, ending the charge. Setting it to 0 prevents bounce offs from happening at all. But I'm not sure what the unit there is exactly.

It's either from a point perpendicular to the wall which gives it a range of +-90, or it's parallel to the wall which gives it a range of 0-180. Or it's something else completely, MHW does weird things sometimes.
Having charged with lance probably only a handful of times, I can't say any more that that. Just educated guesses.

The steering one baffles me. If it was some sort of angular sensitivity, higher would increase speed but you say it doesn't.
¯\\_(ツ)_/¯

I reworded the stuff a bit to fit them. Let me know if this looks good.

![image](https://user-images.githubusercontent.com/1075166/98176441-91003580-1ec6-11eb-9618-268e9e131b94.png)

PS: Next time, either re-open the issue, or better, just make a new one. If you just add stuff to a closed issue (and leave it closed) I'm much more likely to miss it.

**Comment by Schinkikami** [comment]
Yeah clicked on the wrong button .... :D Wanted to reopen.
Everything looks fine. 

Unk126 (the last one in the section) is the time for Guard Up to come up, when using power guard.
