### ISSUE TITLE
(.wp_dat/_g), (.am_dat) & (.itm)?

### ISSUE THREAD

**Issue by JSLJ23** [Synthlight/MHW-Editor#6]
In which directory are the Weapons (.wp_dat/_g), Armors (.am_dat) & Items (.itm) stored for this latest update?

**Comment by Synthlight** [comment]
The update did not change where files are stored.
Modded files go in nativePC.
To get the raw files, extract them from the latest chunk that has them.

Weapon & armor dat files are in common/equip & item data is in common/item.
