### ISSUE TITLE
pl_param

### ISSUE THREAD

**Issue by dtlnor** [Synthlight/MHW-Editor#7]
mistake

**Comment by dtlnor** [comment]
shit noting, CE read data different form it, Gunner Defense Rate correct

**Comment by dtlnor** [comment]
give you some data.
after
Wp MR Augment Defense (4)
the 4 uint8 is
Wp MR Augment Defense Percent Activation 1
Wp MR Augment Defense Percent Activation 2
Wp MR Augment Defense Percent Activation 3
Wp MR Augment Defense Percent Activation 4
Wp MR Augment Defense Percent Reduction (1)	0.7	float
Wp MR Augment Defense Percent Reduction (2)	0.7	float
Wp MR Augment Defense Percent Reduction (3)	0.7	float
Wp MR Augment Defense Percent Activation (4)	0.5	float

**Comment by dtlnor** [comment]
after
Wp MR Augment Element (4) | 12 | uInt8

it is bow status gun ammo 4*uint8
and 2 unknown float data
and the following is 13 float data means the modifier of Augment Element with every weapon

**Comment by dtlnor** [comment]
for pl_skill_param
start from Unk33
you may referencing this https://t.co/eiqC1VKCZ9?amp=1

**Comment by Synthlight** [comment]
![image](https://user-images.githubusercontent.com/1075166/75632387-7bb16980-5bc9-11ea-92d2-4df6916299cf.png)

As for the elemental stuff, there's 14 total weapons, not 13. Bow coatings also looked off by two floats, so this is my guess from the data you suggest:
![image](https://user-images.githubusercontent.com/1075166/75632843-e8c6fe00-5bcd-11ea-9208-f46b595a43fe.png)


I don't understand how the Frostcraft table fits in here, but there's the list with offsets if it helps:
![image](https://user-images.githubusercontent.com/1075166/75632915-95a17b00-5bce-11ea-9022-2aeaea620aee.png)

**Comment by Synthlight** [comment]
I had help with the testing and the new MR augment stuff is confirmed. Thanks for the info.

**Comment by Synthlight** [comment]
I'm also looking at the wrong file for Frostcraft. Nevermind. Will look further into it. It does seem right.

**Comment by Synthlight** [comment]
Added a lot of frostcraft stuff:
![image](https://user-images.githubusercontent.com/1075166/75635031-d0141380-5be0-11ea-8c09-ccead73bd29a.png)
![image](https://user-images.githubusercontent.com/1075166/75635038-de622f80-5be0-11ea-9eb0-fd993d419faa.png)
![image](https://user-images.githubusercontent.com/1075166/75635046-f3d75980-5be0-11ea-9e2f-158481b87b77.png)

Not sure what the three odd ones are in the middle.

**Comment by Synthlight** [comment]
Added. Will be in the next released version.
