### ISSUE TITLE
thxs for your amazing work.Can this tool decrypt and encrypt .shlp files?

### ISSUE THREAD

**Issue by Einstein8** [Synthlight/MHW-Editor#9]

**Comment by Synthlight** [comment]
Use the command line param: https://github.com/Synthlight/MHW-Editor/wiki#command-line-params
Yes. And 1.8 should have it as a know key: https://github.com/Synthlight/MHW-Editor/blob/v1.18/MHW-Template/EncryptionKeys.cs#L36
